server:
  port: 7777
spring:
  # DataSource Config
  datasource:
    driver-class-name: org.h2.Driver
    # 配置h2数据库的连接地址（嵌入式）
    url: jdbc:h2:./data/my_db;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1;MODE=MYSQL;
    username: sa
    password: 1
    # 连接池配置
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: itplhHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  # H2 Config
  h2:
    console:
      # 开启web console功能
      enabled: true
      # 默认 /h2-console
      path: /h2
  sql:
    init:
      # 每次启动程序，程序都会运行sql文件，对数据库的数据操作
      mode: ALWAYS
      schema-locations: classpath:/db/schema.sql
      data-locations: classpath:/db/data.sql

# Mybatis Plus Config
mybatis-plus:
  mapper-locations: classpath*:com/example/demo/**/xml/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true
